### ISSUE TITLE
Error when getting field "yawVelocity"

### ISSUE THREAD

**Issue by KxmischesDomi** [KxmischesDomi/BoatContainer#1]
```java
[14:08:52] [Server thread/INFO]: [STDERR]: java.lang.NoSuchFieldException: yawVelocity
[14:08:52] [Server thread/INFO]: [STDERR]: at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[14:08:52] [Server thread/INFO]: [STDERR]: at de.kxmischesdomi.boatcontainer.common.entity.CustomBoatEntity.getYawVelocity(CustomBoatEntity.java:65)
[14:08:52] [Server thread/INFO]: [STDERR]: at de.kxmischesdomi.boatcontainer.common.entity.CustomBoatEntity.method_5865(CustomBoatEntity.java:52)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_1297.method_5842(class_1297.java:1874)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_1309.method_5842(class_1309.java:2790)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_1657.method_5842(class_1657.java:523)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_3218.method_18763(class_3218.java:678)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_3218.method_18762(class_3218.java:659)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_1937.method_18472(class_1937.java:483)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_3218.method_31420(class_3218.java:417)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_5574.method_31791(class_5574.java:54)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_3218.method_18765(class_3218.java:392)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.class_3176.method_3813(class_3176.java:335)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
[14:08:52] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[14:08:52] [Server thread/INFO]: [STDERR]: at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by KxmischesDomi** [comment]
Should be fixed with https://github.com/KxmischesDomi/BoatContainer/commit/fec579288a5eb661cfc9bf1b68922d1dfbff9600
