### ISSUE TITLE
Spam in Console due to Modded Boats not being gracefully handled if mod is not installed

### ISSUE THREAD

**Issue by MagnusRevang** [KxmischesDomi/BoatContainer#19]
F.ex if you don't have the mod Twigs installed, BoatContainer still assumes it will find it and spams the console with errors:

[11:47:45] [Worker-Main-3/ERROR]: Parsing error loading recipe boatcontainer:stripped_bamboo_chest_boat
com.google.gson.JsonSyntaxException: Unknown item 'twigs:stripped_bamboo_boat'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8144(class_1867.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:83) ~[server-intermediary.jar:?]
	at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

I'm sure this can be more gracefully handled

**Comment by DomiIRL** [comment]
I'll look for solutions but this doesn't really impact the gameplay at all.

**Comment by DomiIRL** [comment]
Fixed in newest update
