### ISSUE TITLE
Error while starting server/world

### ISSUE THREAD

**Issue by Eatham532** [KxmischesDomi/BoatContainer#26]
Error shown bellow:

```shell
[16:25:16] [Server thread/ERROR]: Parsing error loading recipe boatcontainer:stripped_bamboo_ender_chest_boat
com.google.gson.JsonSyntaxException: Unknown item 'twigs:stripped_bamboo_boat'
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe:253) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.recipe.ShapedRecipe.getItem(ShapedRecipe:253) ~[?:?]
at net.minecraft.recipe.Ingredient.entryFromJson(Ingredient:162) ~[?:?]
at net.minecraft.recipe.Ingredient.fromJson(Ingredient:145) ~[?:?]
at net.minecraft.recipe.ShapelessRecipe$Serializer.getIngredients(ShapelessRecipe:98) ~[?:?]
at net.minecraft.recipe.ShapelessRecipe$Serializer.read(ShapelessRecipe:83) ~[?:?]
at net.minecraft.recipe.ShapelessRecipe$Serializer.read(ShapelessRecipe:79) ~[?:?]
at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:135) ~[?:?]
at net.minecraft.recipe.RecipeManager.apply(RecipeManager:56) ~[?:?]
at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:776) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:160) ~[server-intermediary.jar:?]
at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:758) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) ~[server-intermediary.jar:?]
at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
at net.minecraft.server.MinecraftServer.reloadResources(MinecraftServer:1316) ~[server-intermediary.jar:?]
at net.minecraft.server.command.ReloadCommand.tryReloadDataPacks(ReloadCommand:22) ~[?:?]
at net.minecraft.server.command.ReloadCommand.method_13530(ReloadCommand:53) ~[?:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
at net.minecraft.server.command.CommandManager.redirect$zcg000$performCommand(CommandManager:1047) ~[?:?]
at net.minecraft.server.command.CommandManager.execute(CommandManager:261) ~[?:?]
at net.minecraft.server.command.CommandManager.executeWithPrefix(CommandManager:254) ~[?:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.executeQueuedCommands(MinecraftDedicatedServer:305) ~[?:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:290) ~[?:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$zig000$modifiedRunLoop(MinecraftServer:3380) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
[16:25:16] [Server thread/ERROR]: Parsing error loading recipe boatcontainer:stripped_bamboo_furnace_boat
com.google.gson.JsonSyntaxException: Unknown item 'twigs:stripped_bamboo_boat'
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at net.minecraft.recipe.ShapedRecipe.method_17878(ShapedRecipe:253) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.recipe.ShapedRecipe.getItem(ShapedRecipe:253) ~[?:?]
at net.minecraft.recipe.Ingredient.entryFromJson(Ingredient:162) ~[?:?]
at net.minecraft.recipe.Ingredient.fromJson(Ingredient:145) ~[?:?]
at net.minecraft.recipe.ShapelessRecipe$Serializer.getIngredients(ShapelessRecipe:98) ~[?:?]
at net.minecraft.recipe.ShapelessRecipe$Serializer.read(ShapelessRecipe:83) ~[?:?]
at net.minecraft.recipe.ShapelessRecipe$Serializer.read(ShapelessRecipe:79) ~[?:?]
at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:135) ~[?:?]
at net.minecraft.recipe.RecipeManager.apply(RecipeManager:56) ~[?:?]
at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:776) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:160) ~[server-intermediary.jar:?]
at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:758) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) ~[server-intermediary.jar:?]
at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
at net.minecraft.server.MinecraftServer.reloadResources(MinecraftServer:1316) ~[server-intermediary.jar:?]
at net.minecraft.server.command.ReloadCommand.tryReloadDataPacks(ReloadCommand:22) ~[?:?]
at net.minecraft.server.command.ReloadCommand.method_13530(ReloadCommand:53) ~[?:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
at net.minecraft.server.command.CommandManager.redirect$zcg000$performCommand(CommandManager:1047) ~[?:?]
at net.minecraft.server.command.CommandManager.execute(CommandManager:261) ~[?:?]
at net.minecraft.server.command.CommandManager.executeWithPrefix(CommandManager:254) ~[?:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.executeQueuedCommands(MinecraftDedicatedServer:305) ~[?:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:290) ~[?:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$zig000$modifiedRunLoop(MinecraftServer:3380) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by DomiIRL** [comment]
This is just a recipe loading error that is caused because a specific mod I added compatibility with isn't installed.
It won't cause any problems with the functionality of the mod.

**Comment by Eatham532** [comment]
Yeh, i thought so. Is it possible to make it check if twigs is installed because it is annoying to see that massive errer and also other people might think there is something wrong.
