### ISSUE TITLE
Non [a-z0-9/._-] character in path of location boatcontainer:twigs:stripped_bamboo_chest_boat

### ISSUE THREAD

**Issue by Jurklein** [KxmischesDomi/BoatContainer#30]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'boatcontainer'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: website/skylorbeck/minecraft/skylorlib/MidnightConfig
		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
		at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
		at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		at website.skylorbeck.minecraft.difficultyplus.Difficultyplus.onInitialize(Difficultyplus.java:15)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 7 more
	Caused by: java.lang.ClassNotFoundException: website.skylorbeck.minecraft.skylorlib.MidnightConfig
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		... 17 more
Caused by: java.lang.ExceptionInInitializerError
	at de.kxmischesdomi.boatcontainer.BoatContainer.onInitialize(BoatContainer.java:13)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: boatcontainer:twigs:stripped_bamboo_chest_boat
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at de.kxmischesdomi.boatcontainer.common.registry.ModItems.register(ModItems.java:65)
	at de.kxmischesdomi.boatcontainer.common.registry.ModItems.registerBoat(ModItems.java:56)
	at de.kxmischesdomi.boatcontainer.common.registry.ModItems.<clinit>(ModItems.java:37)
	... 9 more

Tested along with Better Minecraft Fabric v1.19 Modpack.

**Comment by DomiIRL** [comment]
Seems like twigs messed something up in the 1.19 update. Don't know what it is and don't got time to look into that deeper.
Added a catch that the mod won't crash in the newest version.

**Comment by DomiIRL** [comment]
Fixed in the newest update
